### ISSUE TITLE
Avoid scenario naming collisions by identify scenarios based on the contents of the Stubo files

### ISSUE THREAD

**Issue by jimCresswell** [Stub-O-Matic/stubo-app#48]
Please could we have Stubo scenarios (optionally?) identified by a hash of the Stubo file contents? That way updating a stub without changing its name would still start a new session. If the hash matches an existing stub then there will no need to re-import it and the service can just return a 200 (or 304?).

This does risk filling a server up with lots of versions of stubs, which is where #47 comes in.

CC: @sponte @mptully @twinser

**Comment by johnecobo** [comment]
Please confirm my understanding of the problem you hope to solve with this suggestion:

1. tester starts playback on scenario "abc123" the test does not finish for some reason and a Stubo session for abc123 is left hanging in playback mode.
2. the automated test suite starts, The command file for scenario abc123 attempts to delete stubs for abc123 before loading the latest, up to date version of the stubs.
3. the auto-test delete fails because of the hanging playback session.

You want Stubo to leave the hanging session as it might still be needed or in use, but to somehow load and run the latest stubs for scenario abc123. Renaming of abc123 is a possible solution.

**Comment by johnecobo** [comment]
Note that the use of a compressed (.jar) file containing all stubs for a scenario is not required or even standard, so basing a solution on a hash of the .jar is "questionable."

**Comment by johnecobo** [comment]
What was wrong with giving the auto-test suite its own Stubo URL? This would avoid clashes simply.

**Comment by jimCresswell** [comment]
@sponte you want to jump on this?

**Comment by guyrichardson** [comment]
Hello all
@johnecobo @sponte @jimCresswell 

Is this still active?

**Comment by johnecobo** [comment]
I am awaiting responses from my questions above.

**Comment by sponte** [comment]
Sorry for the delay @johnecobo 

This ticket is about identifying the need to upload stubs to the server based on unique hash generated from uploaded jar file. How it would work is:

1. Jenkins agent 1 starts scenario 123 and uploads stubs from http://repo/123.jar
1. Stubo downloads 123.jar and generates unique hash from the file, potentially using md5 and then stores stubs internally using unique hash key
1. While scenario 123 is running on jenkins agent 1, another agent, jenkins 2 is starting to run the same scenario and tries to upload 123.jar
1. Stubo downloads 123.jar and generates unique hash from the jar file. Before executing commands, stubo checks whether it already has stubs for the unique hash, if it does it doesn't do anything, if 123.jar has changed, different md5 hash will be generated and stubs will be uploaded under new key

With this functionality in place, we would not be deleting stubs through our scripts, instead we would use TTL on the stubs as described under #47 

This with the combination of weblogic session id would provide resilience and flexibility for running multiple parallel test cases.

**Comment by johnecobo** [comment]
Perhaps we can discuss this tomorrow. The proposal sounds like putting giving Stubo the responsibility for version control, which seems unfair to me. :)  If the problem is your sessions attempting to delete a scenario which is in playback or record here is another alternative:

1. The test tool creates scenario names based on a hash of the stubs, so if stubs have changed since the last load to Stubo, there is no chance of a clash and new stubs will be uploaded.
2. The test tool ensures session names are unique (random nbr.?)
3. Make Stubo less strict and allow "errors" in command files, eg. ignore errors in delete/stubs and put/stubs. This would mean that if a scenario with the same name existed and was in playback or record, all commands to mess with it would effectively be ignored, but the begin/session?mode=playback&session=456 would work and the test could continue.

This seems a bit ugly and would need careful consideration. To do this one would need to pass scenario names as arguments to command files as we have done with session names.

Another option is to abandon command files entirely. They are just a shorthand for simple batches of Stubo API calls. You can programatically do whatever you want using the Stubo API which might be better for you as you can deal with failed commands logically.

**Comment by guyrichardson** [comment]
I would recommend that Jenkins generates a unique scenario name each time it tries to upload stubs.

**Comment by guyrichardson** [comment]
The scenario should be deleted on completion of the test run

**Comment by guyrichardson** [comment]
Superseded by
https://github.com/Stub-O-Matic/stubo-app/issues/52
